
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.uelbosque.interprete.parser;

/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MODEL_NAME = 2;
  public static final int MODEL_DESCRIPTION = 6;
  public static final int INPUTS = 11;
  public static final int LBRACKET = 34;
  public static final int REGRESSION = 30;
  public static final int OUTPUT_TYPE = 10;
  public static final int OUTPUT = 8;
  public static final int INPUT = 12;
  public static final int MODEL = 15;
  public static final int ANN = 24;
  public static final int LAYER = 17;
  public static final int FREETEXT = 20;
  public static final int RANDOMFOREST = 26;
  public static final int LAYERS = 16;
  public static final int CLASSIFIER = 29;
  public static final int COMMA = 37;
  public static final int OUTPUT_NAME = 9;
  public static final int MODEL_FAMILY = 3;
  public static final int LAYER_PARAMS = 19;
  public static final int EOF = 0;
  public static final int RBRACKET = 35;
  public static final int SVM = 27;
  public static final int error = 1;
  public static final int INPUT_TYPE = 14;
  public static final int LAYER_NAME = 18;
  public static final int NUMBER = 22;
  public static final int CLUSTERING = 31;
  public static final int DECISIONTREE = 28;
  public static final int CATEGORICAL = 21;
  public static final int MODEL_TYPE_NAME = 5;
  public static final int COLON = 36;
  public static final int MODEL_TYPE = 4;
  public static final int LBRACE = 32;
  public static final int TREE = 25;
  public static final int OUTPUTS = 7;
  public static final int RBRACE = 33;
  public static final int INPUT_NAME = 13;
  public static final int BINARY = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MODEL_NAME",
  "MODEL_FAMILY",
  "MODEL_TYPE",
  "MODEL_TYPE_NAME",
  "MODEL_DESCRIPTION",
  "OUTPUTS",
  "OUTPUT",
  "OUTPUT_NAME",
  "OUTPUT_TYPE",
  "INPUTS",
  "INPUT",
  "INPUT_NAME",
  "INPUT_TYPE",
  "MODEL",
  "LAYERS",
  "LAYER",
  "LAYER_NAME",
  "LAYER_PARAMS",
  "FREETEXT",
  "CATEGORICAL",
  "NUMBER",
  "BINARY",
  "ANN",
  "TREE",
  "RANDOMFOREST",
  "SVM",
  "DECISIONTREE",
  "CLASSIFIER",
  "REGRESSION",
  "CLUSTERING",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "COLON",
  "COMMA"
  };
}

